name: Callability
description: "Start a conversation"
publish_to: 'none'
version: 0.5.0+9

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.7
  #shared_preferences: ^2.3.2

  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  objectbox: ^4.0.2
  objectbox_flutter_libs:
  path_provider: ^2.1.4
  flutter_contacts: ^1.1.9+2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  logging_flutter: ^3.0.0
  package_info_plus: ^8.0.2
  device_info_plus: ^11.0.0
  test:

  build_runner: ^2.0.0
  objectbox_generator: any
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_database: ^11.1.4
  google_sign_in: ^6.2.1
  protobuf: ^3.1.0
  relative_time: ^5.0.0
  grpc: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
